### ISSUE TITLE
non existing Spark version in part2 

### ISSUE THREAD

**Issue by mand35** [smart-data-lake/getting-started#4]
Hi, 
in the part `part2.additional-files.zip/polynote/Dockerfile`  the Spark version 3.2.0 is defined. When running the `docker-compose build` it tries to download the package from [Spark downloads](https://dlcdn.apache.org/spark/), but there does only the following versions exist:

```
[DIR] [spark-2.4.8/](https://dlcdn.apache.org/spark/spark-2.4.8/)            2021-05-14 23:46    -   
[DIR] [spark-3.0.3/](https://dlcdn.apache.org/spark/spark-3.0.3/)            2021-06-23 07:39    -   
[DIR] [spark-3.1.2/](https://dlcdn.apache.org/spark/spark-3.1.2/)            2021-05-27 16:46    -   
[DIR] [spark-3.1.3/](https://dlcdn.apache.org/spark/spark-3.1.3/)            2022-02-18 22:57    -   
[DIR] [spark-3.2.1/](https://dlcdn.apache.org/spark/spark-3.2.1/)            2022-01-26 06:02    - 
```

Thus version may be changed to `ARG SPARK_VERSION="3.2.1"` in the above mentioned Dockerfile.

**Comment by zzeekk** [comment]
@mand35: you're right, we need to change that to 3.2.1. Unfortunately old patch versions are removed from Spark downloads.
